name = "vertex-ai-utilities"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
node_compat = true

[env.production]
name = "vertex-ai-utilities-prod"
vars = { 
  NODE_ENV = "production",
  VERTEX_AI_LOCATION = "us-central1",
  GENKIT_MODEL = "gemini-1.5-pro",
  RATE_LIMIT_WINDOW_MS = "900000",
  RATE_LIMIT_MAX_REQUESTS = "100",
  LOG_LEVEL = "info"
}

[env.staging]
name = "vertex-ai-utilities-staging"
vars = { 
  NODE_ENV = "staging",
  VERTEX_AI_LOCATION = "us-central1",
  GENKIT_MODEL = "gemini-1.5-pro",
  RATE_LIMIT_WINDOW_MS = "900000",
  RATE_LIMIT_MAX_REQUESTS = "100",
  LOG_LEVEL = "debug"
}

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[observability]
enabled = true

[build]
command = "pnpm run build"

[build.upload]
format = "modules"
main = "./dist/worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]