name = "vertex-ai-utilities"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
node_compat = true

[env.production]
name = "vertex-ai-utilities-prod"
vars = { NODE_ENV = "production" }

[env.staging]
name = "vertex-ai-utilities-staging"
vars = { NODE_ENV = "staging" }

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[observability]
enabled = true

[build]
command = "pnpm run build"

[build.upload]
format = "modules"
main = "./dist/worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]